plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - download.md
  - index.md
  - installation.md
  - howto.md

theme: pages-themes/midnight@v0.2.0
