relative_links:
  enabled: true
  collections: true
include:
  - download.md
  - index.md
  - installation.md
  - howto.md

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
